### ISSUE TITLE
AR Optimistic Locking does not work with activerecord-explainer

### ISSUE THREAD

**Issue by eitoball** [yhirano55/activerecord-explainer#2]
With activecrecord-explainer, ActiveRecord's [Optimistic Locking](https://edgeguides.rubyonrails.org/active_record_querying.html#optimistic-locking) doesn't work.  When you update model with lower `lock_version`, it will fail to update, but it doesn't raise `ActiveRecord::StaleObjectError`.

It seems that `ActiveRecord` relies on `affected_rows`. [It](https://github.com/rails/rails/blob/v6.0.2.2/activerecord/lib/active_record/locking/optimistic.rb#L88-L96) checks if `affected_rows` is `1` or not. If not, it will raise `ActiveRecord::StaleObjectError`.   Because activerecord-explainer issues `EXPLAIN` query after `UPDATE` query, `affected_rows` always `1`, ActiveRecord with activerecord-explainer enabled does not raise `ActiveRecord::StaleObjectError`.

**Comment by yhirano55** [comment]
@eitoball Thanks for your reporting. I'm sorry its reply is too late :bow:

Could you open a pull request to fix this problem?

**Comment by eitoball** [comment]
@yhirano55 Tried #4.
